### ISSUE TITLE
Tags Auto-completion

### ISSUE THREAD

**Issue by kra3** [tests-assistant/tests-assistant#21]
I was thinking about a simple auto completion while filling tags field.
It needs some JS wizardry (jQuery is there to rescue)

What I was thinking was, add a custom routing to get list of tags which contains user entered characters in them in json format. Feed it a custom jquery function to show a list to choose from.

Then, the lazy side of me found this: http://code.drewwilson.com/entry/autosuggest-jquery-plugin

I don't know the behavior of that plugin if a tags is not found. (ie., will it create a new tag or just ignore it)

This is an alternative to #17 (depends on how much work you have to do, or how much motivated you are: choose one :hamburger: )

Oh yes, Question is: Which method to implement? #21 or #17

**Comment by ghost** [comment]
I prefer #17 I already started it, it's not very difficult.

**Comment by kra3** [comment]
It is just a question. Nothing to worry about. 
I'm too lazy to implement any #21 anyways :)

So, closing #21

**Comment by ghost** [comment]
Sorry I did not explain why I prefer the tag cloud select. The autocompletion tool you mention looks good, but if you don't know which tag to use, you will still need to look for them somewhere. Since we don't have much tags the cloud tag select can work better that autocompletion. I'm pushing a demo in a few seconds tell me what you think :8ball:

**Comment by ghost** [comment]
Otherwise said, situation where:
- The number of tags is big
- You don't care if the spelling is creative 
- Last but not least you don't want to suggest a search but help the user

Whereas Tag cloud select is good for this situation (kind of opposite):
- Number of tags is small
- Spelling is critical
- Also we want to suggest tags because i want to keep to number of tags small. So before creating a new one he need to review the existing one.

Anyway pushing tag cloud select deluxe (demo) rightaway ;)

**Comment by kra3** [comment]
nice demo btw
